### ISSUE TITLE
could not find channel

### ISSUE THREAD

**Issue by scavenrage** [t-8ch/binding-linuxinput#5]
Hi,
I installed the binding and everything works fine except for 1 button.
I have a remote that works like a mouse and a keyboard. This particular key is like pressing the right mouse button.
This warning appears

12:04:55.009 [WARN ] [linuxinput.internal.LinuxInputHandler] - Could not find channel for code 273

Is it possible to manually add this channel?
Thanks!

**Comment by t-8ch** [comment]
Hi @scavenrage,
Support for mouse buttons could indeed be added.
I put it on my TODO list.

**Comment by scavenrage** [comment]
Thank you very much for your quick answer!
until mouse buttons will be available, I'm using a bash script that use "evtest" to capture inputs and to send to an item these values, if anyone else is interested!

**Comment by t-8ch** [comment]
FYI, as this binding is now part of OpenHAB proper you should open further tickets / question / workarounds on the official OpenHAB channels. And also mention/ping me on them, so I become aware.
This repo is only there for historical reasons.

**Comment by t-8ch** [comment]
Link to the forum discussion: https://community.openhab.org/t/linuxinput-binding-and-mouse-capture/122612
